apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-reader-cr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-crb
subjects:
- kind: ServiceAccount
  name: cluster-reader-sa
  namespace: demo
roleRef:
  kind: ClusterRole
  name: cluster-reader-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-reader-sa
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kproxy
  name: kproxy
spec:
  serviceAccountName: cluster-reader-sa 
  containers:
  - image: ghcr.io/suren-m/utils:alpine
    name: kproxy
    resources: {}
    command: ["/bin/sh", "-c", "--"]     
    args: ["while true; do sleep 10; done;"]
    env: 
      - name: NODE_NAME
        valueFrom:
          fieldRef:
           fieldPath: spec.nodeName
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
  - image: bitnami/kubectl:latest
    name: kubectl
    args: ["proxy"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
