apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: ${ClusterMIClientId}
  labels:
    azure.workload.identity/use: "true"
  name: "appserviceaccount"
  namespace: default