apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tenant1
  labels:
    istio-injection: enabled
spec: {}
status: {}

---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: tenant2
spec: {}
status: {}
